//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.DSPMPVSCDProyectoIPS
{
	/// <summary>
	/// DomainModel DSPMPVSCDProyectoIPSDomainModel
	/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("bcdf2971-6400-4c1a-beee-ea4400c69d7b")]
	public partial class DSPMPVSCDProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DSPMPVSCDProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xbcdf2971, 0x6400, 0x4c1a, 0xbe, 0xee, 0xea, 0x44, 0x00, 0xc6, 0x9d, 0x7b);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DSPMPVSCDProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(TapizDiagramaClases),
				typeof(Atributo),
				typeof(Operacion),
				typeof(Clase),
				typeof(EstiloOperacion),
				typeof(ClaseEnriquecida),
				typeof(EstiloClase),
				typeof(EstiloAtributo),
				typeof(TapizDiagramaClasesHasClases),
				typeof(ClaseHasAtributo),
				typeof(ClaseHasOperacion),
				typeof(ClaseHeredaClase),
				typeof(ClaseEnriquecidaHasEstiloClases),
				typeof(ClaseEnriquecidaHasEstiloAtributo),
				typeof(ClaseEnriquecidaHasEstiloOperacioned),
				typeof(ClaseAgregaClase),
				typeof(ClaseComponeClase),
				typeof(ClaseAsociaClase),
				typeof(DSPMPVSCDProyectoIPSDiagram),
				typeof(MetaforaHerencia),
				typeof(MetaforaAgregacion),
				typeof(MetaforaComposicion),
				typeof(MetaforaAsociacion),
				typeof(MetaforaClase),
				typeof(MetaforaAtributo),
				typeof(MetaforaOperacion),
				typeof(MetaforaClaseEnriquecida),
				typeof(MetaforaEstiloClase),
				typeof(MetaforaEstiloAtributo),
				typeof(MetaforaEstiloOperacion),
				typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(TapizDiagramaClases), "solucionDiagrama", TapizDiagramaClases.solucionDiagramaDomainPropertyId, typeof(TapizDiagramaClases.solucionDiagramaPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Nombre", Atributo.NombreDomainPropertyId, typeof(Atributo.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TipoDato", Atributo.TipoDatoDomainPropertyId, typeof(Atributo.TipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "NombreYTipo", Atributo.NombreYTipoDomainPropertyId, typeof(Atributo.NombreYTipoPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "Nombre", Operacion.NombreDomainPropertyId, typeof(Operacion.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "ConjuntoDatos", Operacion.ConjuntoDatosDomainPropertyId, typeof(Operacion.ConjuntoDatosPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "NombreYParametros", Operacion.NombreYParametrosDomainPropertyId, typeof(Operacion.NombreYParametrosPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "Nombre", Clase.NombreDomainPropertyId, typeof(Clase.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "TipoLetra", EstiloOperacion.TipoLetraDomainPropertyId, typeof(EstiloOperacion.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloOperacion), "ColorLetra", EstiloOperacion.ColorLetraDomainPropertyId, typeof(EstiloOperacion.ColorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "ColorFondo", EstiloClase.ColorFondoDomainPropertyId, typeof(EstiloClase.ColorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "ColorLetra", EstiloClase.ColorLetraDomainPropertyId, typeof(EstiloClase.ColorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "TipoLetra", EstiloClase.TipoLetraDomainPropertyId, typeof(EstiloClase.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloClase), "Alineacion", EstiloClase.AlineacionDomainPropertyId, typeof(EstiloClase.AlineacionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "TipoLetra", EstiloAtributo.TipoLetraDomainPropertyId, typeof(EstiloAtributo.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloAtributo), "ColorLetra", EstiloAtributo.ColorLetraDomainPropertyId, typeof(EstiloAtributo.ColorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseHeredaClase), "TipoHerencia", ClaseHeredaClase.TipoHerenciaDomainPropertyId, typeof(ClaseHeredaClase.TipoHerenciaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseAgregaClase), "Nombre", ClaseAgregaClase.NombreDomainPropertyId, typeof(ClaseAgregaClase.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseAgregaClase), "CardinalidadIzquierda", ClaseAgregaClase.CardinalidadIzquierdaDomainPropertyId, typeof(ClaseAgregaClase.CardinalidadIzquierdaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseAgregaClase), "CardinalidadDerecha", ClaseAgregaClase.CardinalidadDerechaDomainPropertyId, typeof(ClaseAgregaClase.CardinalidadDerechaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseComponeClase), "Nombre", ClaseComponeClase.NombreDomainPropertyId, typeof(ClaseComponeClase.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseComponeClase), "CardinalidadIzquierda", ClaseComponeClase.CardinalidadIzquierdaDomainPropertyId, typeof(ClaseComponeClase.CardinalidadIzquierdaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseComponeClase), "CardinalidadDerecha", ClaseComponeClase.CardinalidadDerechaDomainPropertyId, typeof(ClaseComponeClase.CardinalidadDerechaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseAsociaClase), "Nombre", ClaseAsociaClase.NombreDomainPropertyId, typeof(ClaseAsociaClase.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseAsociaClase), "CardinalidadIzquierda", ClaseAsociaClase.CardinalidadIzquierdaDomainPropertyId, typeof(ClaseAsociaClase.CardinalidadIzquierdaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseAsociaClase), "CardinalidadDerecha", ClaseAsociaClase.CardinalidadDerechaDomainPropertyId, typeof(ClaseAsociaClase.CardinalidadDerechaPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizDiagramaClasesHasClases), "TapizDiagramaClases", TapizDiagramaClasesHasClases.TapizDiagramaClasesDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizDiagramaClasesHasClases), "Clase", TapizDiagramaClasesHasClases.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Clase", ClaseHasAtributo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Atributo", ClaseHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "Clase", ClaseHasOperacion.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "Operacion", ClaseHasOperacion.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHeredaClase), "SourceClase", ClaseHeredaClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHeredaClase), "TargetClase", ClaseHeredaClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloClases), "ClaseEnriquecida", ClaseEnriquecidaHasEstiloClases.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloClases), "EstiloClase", ClaseEnriquecidaHasEstiloClases.EstiloClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloAtributo), "ClaseEnriquecida", ClaseEnriquecidaHasEstiloAtributo.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloAtributo), "EstiloAtributo", ClaseEnriquecidaHasEstiloAtributo.EstiloAtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloOperacioned), "ClaseEnriquecida", ClaseEnriquecidaHasEstiloOperacioned.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasEstiloOperacioned), "EstiloOperacion", ClaseEnriquecidaHasEstiloOperacioned.EstiloOperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAgregaClase), "SourceClase", ClaseAgregaClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAgregaClase), "TargetClase", ClaseAgregaClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseComponeClase), "SourceClase", ClaseComponeClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseComponeClase), "TargetClase", ClaseComponeClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAsociaClase), "SourceClase", ClaseAsociaClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAsociaClase), "TargetClase", ClaseAsociaClase.TargetClaseDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(20);
				createElementMap.Add(typeof(TapizDiagramaClases), 0);
				createElementMap.Add(typeof(Atributo), 1);
				createElementMap.Add(typeof(Operacion), 2);
				createElementMap.Add(typeof(Clase), 3);
				createElementMap.Add(typeof(EstiloOperacion), 4);
				createElementMap.Add(typeof(ClaseEnriquecida), 5);
				createElementMap.Add(typeof(EstiloClase), 6);
				createElementMap.Add(typeof(EstiloAtributo), 7);
				createElementMap.Add(typeof(DSPMPVSCDProyectoIPSDiagram), 8);
				createElementMap.Add(typeof(MetaforaHerencia), 9);
				createElementMap.Add(typeof(MetaforaAgregacion), 10);
				createElementMap.Add(typeof(MetaforaComposicion), 11);
				createElementMap.Add(typeof(MetaforaAsociacion), 12);
				createElementMap.Add(typeof(MetaforaClase), 13);
				createElementMap.Add(typeof(MetaforaAtributo), 14);
				createElementMap.Add(typeof(MetaforaOperacion), 15);
				createElementMap.Add(typeof(MetaforaClaseEnriquecida), 16);
				createElementMap.Add(typeof(MetaforaEstiloClase), 17);
				createElementMap.Add(typeof(MetaforaEstiloAtributo), 18);
				createElementMap.Add(typeof(MetaforaEstiloOperacion), 19);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new TapizDiagramaClases(partition, propertyAssignments);
				case 1: return new Atributo(partition, propertyAssignments);
				case 2: return new Operacion(partition, propertyAssignments);
				case 3: return new Clase(partition, propertyAssignments);
				case 4: return new EstiloOperacion(partition, propertyAssignments);
				case 5: return new ClaseEnriquecida(partition, propertyAssignments);
				case 6: return new EstiloClase(partition, propertyAssignments);
				case 7: return new EstiloAtributo(partition, propertyAssignments);
				case 8: return new DSPMPVSCDProyectoIPSDiagram(partition, propertyAssignments);
				case 9: return new MetaforaHerencia(partition, propertyAssignments);
				case 10: return new MetaforaAgregacion(partition, propertyAssignments);
				case 11: return new MetaforaComposicion(partition, propertyAssignments);
				case 12: return new MetaforaAsociacion(partition, propertyAssignments);
				case 13: return new MetaforaClase(partition, propertyAssignments);
				case 14: return new MetaforaAtributo(partition, propertyAssignments);
				case 15: return new MetaforaOperacion(partition, propertyAssignments);
				case 16: return new MetaforaClaseEnriquecida(partition, propertyAssignments);
				case 17: return new MetaforaEstiloClase(partition, propertyAssignments);
				case 18: return new MetaforaEstiloAtributo(partition, propertyAssignments);
				case 19: return new MetaforaEstiloOperacion(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(10);
				createElementLinkMap.Add(typeof(TapizDiagramaClasesHasClases), 0);
				createElementLinkMap.Add(typeof(ClaseHasAtributo), 1);
				createElementLinkMap.Add(typeof(ClaseHasOperacion), 2);
				createElementLinkMap.Add(typeof(ClaseHeredaClase), 3);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasEstiloClases), 4);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasEstiloAtributo), 5);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasEstiloOperacioned), 6);
				createElementLinkMap.Add(typeof(ClaseAgregaClase), 7);
				createElementLinkMap.Add(typeof(ClaseComponeClase), 8);
				createElementLinkMap.Add(typeof(ClaseAsociaClase), 9);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizDiagramaClasesHasClases(partition, roleAssignments, propertyAssignments);
				case 1: return new ClaseHasAtributo(partition, roleAssignments, propertyAssignments);
				case 2: return new ClaseHasOperacion(partition, roleAssignments, propertyAssignments);
				case 3: return new ClaseHeredaClase(partition, roleAssignments, propertyAssignments);
				case 4: return new ClaseEnriquecidaHasEstiloClases(partition, roleAssignments, propertyAssignments);
				case 5: return new ClaseEnriquecidaHasEstiloAtributo(partition, roleAssignments, propertyAssignments);
				case 6: return new ClaseEnriquecidaHasEstiloOperacioned(partition, roleAssignments, propertyAssignments);
				case 7: return new ClaseAgregaClase(partition, roleAssignments, propertyAssignments);
				case 8: return new ClaseComponeClase(partition, roleAssignments, propertyAssignments);
				case 9: return new ClaseAsociaClase(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DSPMPVSCDProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DSPMPVSCDProyectoIPSDomainModel.resourceManager == null)
				{
					DSPMPVSCDProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DSPMPVSCDProyectoIPSDomainModel).Assembly);
				}
				return DSPMPVSCDProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DSPMPVSCDProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DSPMPVSCDProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DSPMPVSCDProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DSPMPVSCDProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DSPMPVSCDProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return DSPMPVSCDProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DSPMPVSCDProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DSPMPVSCDProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DSPMPVSCDProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return DSPMPVSCDProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DSPMPVSCDProyectoIPSDeleteClosure : DSPMPVSCDProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DSPMPVSCDProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DSPMPVSCDProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DSPMPVSCDProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.DSPMPVSCDProyectoIPS.TapizDiagramaClasesHasClases.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DSPMPVSCDProyectoIPS.ClaseHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DSPMPVSCDProyectoIPS.ClaseHasOperacion.OperacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DSPMPVSCDProyectoIPS.ClaseEnriquecidaHasEstiloClases.EstiloClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DSPMPVSCDProyectoIPS.ClaseEnriquecidaHasEstiloAtributo.EstiloAtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DSPMPVSCDProyectoIPS.ClaseEnriquecidaHasEstiloOperacioned.EstiloOperacionDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DSPMPVSCDProyectoIPSCopyClosure : DSPMPVSCDProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DSPMPVSCDProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DSPMPVSCDProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DSPMPVSCDProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.DSPMPVSCDProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TTipoHerencia
	/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TTipoHerencia
	{
		/// <summary>
		/// TotalSolapada
		/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia.TotalSolapada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia/TotalSolapada.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
		TotalSolapada,
		/// <summary>
		/// ParcialDisjunta
		/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia.ParcialDisjunta
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia/ParcialDisjunta.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
		ParcialDisjunta,
		/// <summary>
		/// ParcialSolapada
		/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia.ParcialSolapada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia/ParcialSolapada.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
		ParcialSolapada,
		/// <summary>
		/// TotalDisjunta
		/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia.TotalDisjunta
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.TTipoHerencia/TotalDisjunta.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
		TotalDisjunta,
	}
}
namespace UPM_IPS.DSPMPVSCDProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TAlineacion
	/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TAlineacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TAlineacion
	{
		/// <summary>
		/// Izquierda
		/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TAlineacion.Izquierda
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.TAlineacion/Izquierda.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
		Izquierda,
		/// <summary>
		/// Derecha
		/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TAlineacion.Derecha
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.TAlineacion/Derecha.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
		Derecha,
		/// <summary>
		/// Centro
		/// Description for UPM_IPS.DSPMPVSCDProyectoIPS.TAlineacion.Centro
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DSPMPVSCDProyectoIPS.TAlineacion/Centro.Description", typeof(global::UPM_IPS.DSPMPVSCDProyectoIPS.DSPMPVSCDProyectoIPSDomainModel), "UPM_IPS.DSPMPVSCDProyectoIPS.GeneratedCode.DomainModelResx")]
		Centro,
	}
}

