//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.DSPMPVSCDProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DSPMPVSCD_DSLProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DSPMPVSCDProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DSPMPVSCDProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSPMPVSCDProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DSPMPVSCDProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSPMPVSCDProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDSPMPVSCDProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSPMPVSCDProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string DSPMPVSCDProyectoIPSPackageId = "407613d8-6771-415b-a380-b3eb0239ac37";
		
		// Editor factory identifier
		public const string DSPMPVSCDProyectoIPSEditorFactoryId = "de6a7b08-302f-44ee-8522-f6039457d0b6";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DSPMPVSCDProyectoIPSModelExplorerToolWindowId = "99600f56-255a-49a5-b9c0-21c1cc64f3b2";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.DSPMPVSCDProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DSPMPVSCDProyectoIPSCommandSetId = "086b4fa5-df03-47df-83e7-d1db9a71f5b5";
	}
}