//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.DSPMPVSCD_UPMovie
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DSPMPVSCD_DSLUPMovie";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DSPMPVSCD_UPMovie";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DSPMPVSCD_UPMovieDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSPMPVSCD_UPMovieCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DSPMPVSCD_UPMovieExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSPMPVSCD_UPMovieCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDSPMPVSCD_UPMovieExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DSPMPVSCD_UPMovieCommandSetId), 0x0001);
	
		// Package identifier
		public const string DSPMPVSCD_UPMoviePackageId = "1db3b53e-c312-4f3c-905d-e58fb47dac7a";
		
		// Editor factory identifier
		public const string DSPMPVSCD_UPMovieEditorFactoryId = "a68d7015-d17c-4625-aeee-1713e8146ed6";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DSPMPVSCD_UPMovieModelExplorerToolWindowId = "751a2408-0a59-445d-88a6-a3385a81d275";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.DSPMPVSCD_UPMovie
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DSPMPVSCD_UPMovieCommandSetId = "e5818927-8575-42f5-a277-054282795ce0";
	}
}